CREATE TABLE REGIONAL_AGENCY
(
  AGENCY_ID VARCHAR(10) PRIMARY KEY NOT NULL,
  A_NAME VARCHAR (25) NOT NULL,
  A_ADDRESS VARCHAR(100) NOT NULL,
  A_AREA VARCHAR (30),
  BANK_GUARANTEE_VALUE INT NOT NULL,

);


