CREATE TABLE P_ORDER
(
 O_CODE VARCHAR(20) PRIMARY KEY NOT NULL,
 O_VALUE FLOAT,
 O_DATE DATE,
 DELIVARY_DATE DATE,
 DELIVARY_STATUS VARCHAR(30),
 REG_NO VARCHAR(30) FOREIGN KEY REFERENCES PHARMACY(REG_NO),
 NIC VARCHAR(12) FOREIGN KEY REFERENCES EMPLOYEE(NIC), 
);
