CREATE TABLE PHARMACY
(
REG_NO VARCHAR(30)PRIMARY KEY NOT NULL,
PHAR_NAME VARCHAR(50) NOT NULL,
P_ADDRESS VARCHAR(80) NOT NULL,
P_AREA VARCHAR(40),
CONTACT_NO INT NOT NULL,
P_EMAIL VARCHAR(30) NOT NULL,
NIC VARCHAR(12) NOT NULL FOREIGN KEY REFERENCES EMPLOYEE(NIC),
AGENCY_ID VARCHAR(10)FOREIGN KEY REFERENCES REGIONAL_AGENCY(AGENCY_ID)

);

