CREATE TABLE W_STORE 
(
W_ID VARCHAR(10) NOT NULL ,
P_CODE VARCHAR(20) NOT NULL,
FOREIGN KEY (W_ID) REFERENCES WARE_HOUSE(W_ID),
FOREIGN KEY (P_CODE) REFERENCES PRODUCTS(P_CODE),
STOCK_VALUE FLOAT NOT NULL,
PRIMARY KEY(W_ID,P_CODE)
);