CREATE TABLE SUPPLY_PRODUCTS
(
 SUP_ID VARCHAR (10) NOT NULL ,
 P_CODE VARCHAR (20) NOT NULL,
 QUENTITY FLOAT,
 FOREIGN KEY (SUP_ID) REFERENCES SUPPLIER(SUP_ID),
 FOREIGN KEY (P_CODE) REFERENCES PRODUCTS(P_CODE),
 PRIMARY KEY (SUP_ID,P_CODE)
);