CREATE TABLE EMPLOYEE 
(
  NIC VARCHAR(12) PRIMARY KEY NOT NULL,
  E_NAME VARCHAR(30),
  DOB DATE,
  E_ADDRESS VARCHAR(50),
  CONTACT_NO INT,
  AGENCY_ID VARCHAR(10) FOREIGN KEY REFERENCES REGIONAL_AGENCY(AGENCY_ID),

);