CREATE TABLE WARE_HOUSE 
(
 W_ID VARCHAR(10) PRIMARY KEY NOT NULL,
 W_LOCATION VARCHAR(20),
 CONTACT_NO INT NOT NULL,
 AGENCY_ID VARCHAR(10) NOT NULL  FOREIGN KEY REFERENCES REGIONAL_AGENCY(AGENCY_ID)
);