CREATE TABLE ORDER_PRODUCT
(
 P_CODE VARCHAR(20)  NOT NULL,
 O_CODE VARCHAR(20)  NOT NULL,
 QUANTITY INT,
 PER_PRODUCT_COST FLOAT,
 FOREIGN KEY (P_CODE) REFERENCES PRODUCTS(P_CODE),
 FOREIGN KEY (O_CODE) REFERENCES P_ORDER(O_CODE),
 PRIMARY KEY (P_CODE,O_CODE),
);