CREATE TABLE EMPLOYEE
(
   NIC VARCHAR(12) PRIMARY KEY  NOT NULL,
   F_NAME VARCHAR (30) ,
   L_NAME VARCHAR(30),
   DOB DATE,
   ADDRES VARCHAR (50),
    DE_ID VARCHAR(10) FOREIGN KEY REFERENCES DEPRATMENT(DE_ID)
);